config/routes.rb
Rails.application.routes.draw do
  resources :topics
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
root 'topics#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/topic.rb
class Topic < ApplicationRecord
	validates:name,presence:true,uniqueness:true
	validates:facts,presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:name, :facts)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <% if topic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :facts, style: "display: block" %>
    <%= form.text_area :facts %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div id="<%= dom_id topic %>">
  <p>
    <strong>Name:</strong>
    <%= topic.name %>
  </p>

  <p>
    <strong>Facts:</strong>
    <%= topic.facts %>
  </p>

</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Show this topic", @topic %> |
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Topics</h1>

<div id="topics">
  <% @topics.each do |topic| %>
    <%= render topic %>
    <p>
      <%= link_to "Show this topic", topic %>
    </p>
  <% end %>
</div>

<%= link_to "New topic", new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @topic %>

<div>
  <%= link_to "Edit this topic", edit_topic_path(@topic) %> |
  <%= link_to "Back to topics", topics_path %>

  <%= button_to "Destroy this topic", @topic, method: :delete %>
</div>